annotations:
  charts.openshift.io/name: kubestash-certified
apiVersion: v2
appVersion: v2026.1.19
dependencies:
- condition: kubestash-operator.enabled
  name: kubestash-operator
  repository: file://../kubestash-operator
  version: v0.23.0
- condition: kubestash-catalog.enabled
  name: kubestash-catalog
  repository: file://../kubestash-catalog
  version: v2026.1.19
- condition: kubestash-metrics.enabled
  name: kubestash-metrics
  repository: file://../kubestash-metrics
  version: v2026.1.19
- condition: ace-user-roles.enabled
  name: ace-user-roles
  repository: oci://ghcr.io/appscode-charts
  version: v2025.3.14
- condition: global.taskQueue.enabled
  name: taskqueue
  repository: oci://ghcr.io/appscode-charts
  version: v2026.1.15
description: KubeStash by AppsCode - Backup your Kubernetes native applications
home: https://kubestash.com
icon: https://cdn.appscode.com/images/products/kubestash/stash-icon.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubestash-certified
sources:
- https://github.com/kubestash
type: application
version: 2026.1.19
