apiVersion: v2
name: kubestash-metrics
description: KubeStash State Metrics
type: application
version: v2026.1.8-rc.0
appVersion: v2026.1.8-rc.0
kubeVersion: '>=1.28.0'
annotations:
  charts.openshift.io/name: kubestash-metrics
home: https://kubestash.com
icon: https://cdn.appscode.com/images/products/stash/stash-community-icon.png
sources:
- https://github.com/kuebstash
maintainers:
- name: appscode
  email: support@appscode.com
