annotations:
  charts.openshift.io/name: kubestash-certified-crds
apiVersion: v2
appVersion: v2026.2.27
description: Chart containing only CRDs from kubestash chart
home: https://kubestash.com
icon: https://cdn.appscode.com/images/products/kubestash/stash-icon.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubestash-certified-crds
sources:
- https://github.com/kubestash
version: 2026.2.27
